### ISSUE TITLE
Server names hash bucket size.

### ISSUE THREAD

**Issue by ThePixelDeveloper** [FreedomBen/dory#16]
Dory suffers from a problem that the dinghy http proxy has fixed.

```
# Apply fix for very long server names
server_names_hash_bucket_size 128;
```

Otherwise if try to set longer hostnames you just get the default nginx template.

Speaking of your forked image, is there any reason to keep it round because the dinghy image does support SSL.

**Comment by FreedomBen** [comment]
Thanks, I'll get an update in to latest dinghy http proxy.  In the mean time you can work around it by using whichever image you want for the proxy, by just settings a `:dory -> :nginx_proxy -> :image` key in your `dory.yml`.  Example:

```
---
dory:
  nginx_proxy:
    image: codekitchen/dinghy-http-proxy:2.5.8
    enabled: true
    container_name: dory_dinghy_http_proxy
    https_enabled: true
    ssl_certs_dir: ''  # leave as empty string to use default certs
```

The reason I've still kept the forked version around is because it will automagically work on both 80 and 443 even if you don't give it certs (it will use default certs).
