### ISSUE TITLE
can't seem to connect

### ISSUE THREAD

**Issue by jhoogeboom** [FreedomBen/dory#31]
This is on macOS 10.14.3
```
ruby -v
ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-darwin18]
dory -v
Dory - Version: 1.0.3
```
```
version: "2"
services:
  redis:
    image: redis
    environment:
      VIRTUAL_HOST: redis.docker
      VIRTUAL_PORT: 6379
  crccheck:
    image: crccheck/hello-world
    environment:
      VIRTUAL_HOST: hello.docker
      VIRTUAL_PORT: 8000
```

Trying out a Redis and hello-world container, but running into issues, Redis-cli will refuse to connect:

```
redis-cli -h redis.docker ping
Could not connect to Redis at redis.docker:6379: Connection refused
```

while all *.docker respond to the curl of hello-world:
- hello.docker
- anything.docker
